# apiVersion: v1
# data:
#   test.json: |
# {{ .Files.Get "test.json" | indent 4}}
# kind: ConfigMap
# metadata:
#   name: test-config

# ---

apiVersion: v1
data:
  test.json: |
    {
      "production" : "true"
      name: "Akeem"
    }
kind: ConfigMap
metadata:
  name: test-config
  namespace: default
